#lauge
xkb_rules_layout=us, ru
bind=alt,shift_l,switch_keyboard_layout

#window
focuscolor=0x88c0d0ff
bordercolor=0x3b4252ff
border_radius=20
borderpx=0
gappih=5
gappiv=5

gappoh=5
gappov=5

smartgaps=1

bind=SUPER,s,togglefullscreen,

#binds
exec-once=waybar
exec-once=awww-daemon

bind=SUPER,t,spawn,kitty
bind=SUPER,d,spawn,rofi -show drun
bind=SUPER,e,spawn,thunar
bind=SUPER,f,spawn,firefox
bind=SUPER,z,togglefloating
bind=SUPER,w,reload_config
bind=SUPER,q,killclient
bind=SUPER,a,spawn,/home/ellio/.config/rofi/scripts/wallpaper
bind=SUPER,c,spawn,/home/ellio/.config/rofi/scripts/waybar-colors
bind=SUPER,l,spawn,hyprlock
bind=SUPER,v,spawn,eww open --toggle player
bind=SUPER,y,spawn,eww open --toggle control

#workspace 1-9
bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER,6,view,6,0
bind=SUPER,7,view,7,0
bind=SUPER,8,view,8,0
bind=SUPER,9,view,9,0

#animation
animations=1
layer_animations=1
tag_animation_direction=1

blur=10
blur_layer=10           
blur_optimized=12
blur_params_radius=10
blur_params_num_passes=2
blur_params_noise=0.02
blur_params_brightness=0.9
blur_params_contrast=0.9
blur_params_saturation=1.1

layerrule=animation_type_open:zoom,animation_type_close:fade,layer_name:rofi
layerrule=animation_type_open:fade,animation_type_close:fade,layer_name:waybar

#keyboard
disable_while_typing=0

sloppyfocus=1
warpcursor=1

focus_cross_monitor=1

enable_floating_snap=1
snap_distance=30

bind=SUPER,Left,focusdir,left
bind=SUPER,Right,focusdir,right
bind=SUPER,Up,focusdir,up
bind=SUPER,Down,focusdir,down
bind=SUPER+SHIFT,Up,resizewin,+80,+80
bind=SUPER+SHIFT,Up,centerwin
bind=SUPER+SHIFT,Down,resizewin,-80,-80
bind=SUPER+SHIFT,Down,centerwin
bind=SUPER+SHIFT,Left,movewin,-80,+0
bind=SUPER+SHIFT,Right,movewin,+80,+0
bind=SUPER+CTRL,Left,resizewin,-50,+0
bind=SUPER+CTRL,Right,resizewin,+50,+0
bind=SUPER+CTRL,Up,resizewin,+0,-50
bind=SUPER+CTRL,Down,resizewin,+0,+50

mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize

bind=SUPER+ALT,Left,spawn,~/.config/mango/scripts/pan_floating.sh -150 0
bind=SUPER+ALT,Right,spawn,~/.config/mango/scripts/pan_floating.sh 150 0
bind=SUPER+ALT,Up,spawn,~/.config/mango/scripts/pan_floating.sh 0 -150
bind=SUPER+ALT,Down,spawn,~/.config/mango/scripts/pan_floating.sh 0 150
bind=SUPER,Left,spawn,~/.config/mango/scripts/navigate_floating.sh left
bind=SUPER,Right,spawn,~/.config/mango/scripts/navigate_floating.sh right
bind=SUPER,Up,spawn,~/.config/mango/scripts/navigate_floating.sh up
bind=SUPER,Down,spawn,~/.config/mango/scripts/navigate_floating.sh down